# Find the Difference
""" 
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        c = 0
        for cs in s:
            c^=ord(cs)
        for ct in t:
            c^=ord(ct)
        return chr(c)
s = "abcd"
t = "abcde"
sol= Solution()
res = sol.findTheDifference(s,t)
print(res)
""" 
Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 
"""